$body = " 
This is a test mail from 92.
 "
#Notification that a disk drive is reporting an alert for low disk space! 
#$cserver $cdrivelt has $percentFree % free space. Please assign an $priority priority ticket to the $cescinst team. 
#-This is an automated email being generated by the script DiskMonCheck.ps1, as a scheduled task on HQMONP09. 
 
 $SMTPServer = "smtp.gmail.com"

Send-MailMessage -to "aditya.roychoudhary@shell.com" -from "ServerAlert@shell.com" -Subject "Disk Alert - Server running out of disk space!" -body $body -smtpserver $SMTPServer 
#Write-Log  -Message "$($_.Server) Critical alert alogged for the drive $cdrivelt " -Logfile $Logfile 





#152.150.46.25
#Port 25
#SMTP Server Name:
#smtp-eu.shell.com